services:
  snuww-sighting-archive:
    image: ghcr.io/itzcomic/snuwwmovie:latest
    container_name: snuww-sighting-archive
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./:/usr/share/nginx/html
