services:
  snuww-sighting-archive:
    build:
      context: https://github.com/ItzComic/SNUWWmovie.git
    container_name: snuww-sighting-archive
    restart: unless-stopped
    ports:
      - "8088:80"
